data:
  raw_data_path: "data/raw/納品用_20240101_20241231_生鮮全品data.csv"
  encoding: "shift_jis"
  processed_data_path: "data/processed"

feature_engineering:
  baseline_features:
    - "売上単価"
    - "月"
    - "曜日"
    - "週末フラグ"

  time_features:
    enable_time_assignment: false
    enable_congestion: true
    time_distribution_type: "bimodal"

  weather_features:
    enable_weather_api: true
    api_endpoint: "https://api.open-meteo.com/v1/forecast"
    location: "Tokyo"

model:
  algorithm: "ensemble"  # RandomForest, XGBoost, ensemble
  
  # RandomForest設定（Phase 3: L1/L2正則化相当のパラメータ調整）
  n_estimators: 150
  max_depth: 8
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: "sqrt"
  
  # XGBoost設定（Phase 3: L1/L2正則化付き）
  xgb_n_estimators: 100
  xgb_max_depth: 6
  xgb_learning_rate: 0.1
  xgb_reg_alpha: 0.1    # L1正則化
  xgb_reg_lambda: 1.0   # L2正則化
  xgb_subsample: 0.8
  xgb_colsample_bytree: 0.8
  
  random_state: 42
  cv_folds: 5

quality:
  thresholds:
    premium: 0.7
    standard: 0.5
    basic: 0.3

  overfitting_threshold: 0.01

visualization:
  output_dir: "output/visualizations"
  dpi: 300
  style: "want_style"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/demand_forecasting.log"