name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black
          
      - name: Create directories
        run: |
          mkdir -p data/raw data/processed reports logs
          
      - name: Simple smoke test
        run: |
          python -c "print('✓ Python works')"
          
      - name: Test code formatting
        run: |
          black --check src/ tests/
