name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black flake8 isort
          pip install pandas numpy scikit-learn matplotlib pyyaml loguru

      - name: Create directories
        run: |
          mkdir -p data/raw data/processed reports logs

      - name: Syntax check
        run: |
          python -m py_compile src/main.py
          
      - name: Basic test
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/src:$PYTHONPATH"
          python -m pytest tests/test_data.py -v
          
      - name: Code formatting
        run: |
          black --check src/
          
      - name: Success
        run: |
          echo "✅ CI passed successfully"
