name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Verify Python works
        run: |
          python --version
          python -c "print('Hello from CI')"
          
      - name: Install essential dependencies
        run: |
          pip install pytest black pandas numpy scikit-learn matplotlib pyyaml requests loguru
          
      - name: Verify basic structure
        run: |
          ls -la
          test -f src/main.py && echo "main.py exists" || echo "main.py missing"
          test -d tests && echo "tests dir exists" || echo "tests dir missing"
          
      - name: Create required directories
        run: |
          mkdir -p data/raw data/processed reports logs output models
          
      - name: Add src to Python path
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          
      - name: Run simple test (imports tested implicitly)
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python -m pytest tests/test_data.py -v
          
      - name: Check code formatting
        run: |
          black --check src/ tests/
