name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # Test only one version for now

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install essential dependencies only
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas numpy scikit-learn matplotlib seaborn scipy pyyaml requests loguru typer tqdm python-dotenv shap black flake8 isort
          
      - name: Add src to Python path
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          
      - name: Create required directories
        run: |
          mkdir -p data/raw data/processed reports logs output models

      - name: Debug environment
        run: |
          pwd
          ls -la
          ls -la src/
          ls -la src/demand_forecasting/
          
      - name: Basic syntax check step by step
        run: |
          echo "Compiling main.py..."
          python -m py_compile src/main.py
          echo "Testing import..."
          python -c "import sys; print('Python version:', sys.version)"
          python -c "import sys; print('Current working directory:', sys.exc_info())" || true
          python -c "import sys; sys.path.insert(0, 'src'); print('Updated path:', sys.path[:3])"
          python -c "import sys; sys.path.insert(0, 'src'); import demand_forecasting; print('Import successful')"

      - name: Run single test file
        run: |
          python -m pytest tests/test_data.py -v

      - name: Check code formatting with black
        run: |
          black --check src/ tests/
