name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black flake8 isort
          pip install pandas numpy scikit-learn matplotlib seaborn scipy pyyaml requests loguru typer tqdm python-dotenv shap mkdocs

      - name: Create directories
        run: |
          mkdir -p data/raw data/processed reports logs output models reports/figures

      - name: Syntax check
        run: |
          python -m py_compile src/main.py
          
      - name: Run tests
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/src:$PYTHONPATH"
          python -m pytest tests/ -v --tb=short --maxfail=5
          
      - name: Code quality
        run: |
          black --check src/ tests/
          flake8 --max-line-length=99 src/ tests/
          isort --check-only src/ tests/
