name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          
      - name: Setup project environment
        run: |
          mkdir -p data/raw data/processed reports logs output models reports/figures
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/src"
          echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV
          
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          cd ${{ github.workspace }}
          python -m pytest tests/ -v --tb=short --maxfail=3
          
      - name: Check code quality
        run: |
          black --check src/ tests/
          flake8 --max-line-length=99 src/ tests/
          isort --check-only src/ tests/
